[programs.localnet]
merkle_airdrop = "6ejWDiN63M19QaDAwEMw9kWNLrMbmL9SbecY5MejCT8Y"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
